// <auto-generated />
using System;
using FactoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryManagement.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    partial class FactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FactoryManagement.Models.AppSettings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMenuPinned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            Address = "123 Industrial Area",
                            CompanyName = "Factory Management System",
                            CurrencySymbol = "₹",
                            IsMenuPinned = true
                        });
                });

            modelBuilder.Entity("FactoryManagement.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpenseCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryId = 1,
                            CategoryName = "Cab Charges",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7874),
                            Description = "Transportation and cab expenses",
                            DisplayOrder = 1,
                            IconName = "CarSide",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 2,
                            CategoryName = "Transportation Fees",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7878),
                            Description = "General transportation costs",
                            DisplayOrder = 2,
                            IconName = "Truck",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 3,
                            CategoryName = "Freight Charges",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7880),
                            Description = "Shipping and freight costs",
                            DisplayOrder = 3,
                            IconName = "ShippingBox",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 4,
                            CategoryName = "Electricity",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7882),
                            Description = "Electricity bills and charges",
                            DisplayOrder = 4,
                            IconName = "Lightbulb",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 5,
                            CategoryName = "Water",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7885),
                            Description = "Water bills and charges",
                            DisplayOrder = 5,
                            IconName = "Water",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 6,
                            CategoryName = "Internet & Phone",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7887),
                            Description = "Communication expenses",
                            DisplayOrder = 6,
                            IconName = "Wifi",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 7,
                            CategoryName = "Machinery Purchase",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7889),
                            Description = "New machinery and equipment purchases",
                            DisplayOrder = 7,
                            IconName = "Cog",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 8,
                            CategoryName = "Machinery Repair",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7891),
                            Description = "Machine repair and servicing costs",
                            DisplayOrder = 8,
                            IconName = "Wrench",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 9,
                            CategoryName = "Machinery Maintenance",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7893),
                            Description = "Regular maintenance costs",
                            DisplayOrder = 9,
                            IconName = "Tools",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 10,
                            CategoryName = "Fuel",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7895),
                            Description = "Fuel and petroleum expenses",
                            DisplayOrder = 10,
                            IconName = "Gas",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 11,
                            CategoryName = "Generator Diesel",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7897),
                            Description = "Diesel for generators",
                            DisplayOrder = 11,
                            IconName = "Power",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 12,
                            CategoryName = "Rent",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7898),
                            Description = "Facility and equipment rent",
                            DisplayOrder = 12,
                            IconName = "Home",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 13,
                            CategoryName = "Insurance",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7900),
                            Description = "Insurance premiums",
                            DisplayOrder = 13,
                            IconName = "Shield",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 14,
                            CategoryName = "Stationery",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7902),
                            Description = "Office supplies and stationery",
                            DisplayOrder = 14,
                            IconName = "Paperclip",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 15,
                            CategoryName = "Printing",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7904),
                            Description = "Printing and documentation costs",
                            DisplayOrder = 15,
                            IconName = "Printer",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 16,
                            CategoryName = "Legal Fees",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7906),
                            Description = "Legal and compliance costs",
                            DisplayOrder = 16,
                            IconName = "Gavel",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 17,
                            CategoryName = "Accounting Fees",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7908),
                            Description = "Accounting and auditing fees",
                            DisplayOrder = 17,
                            IconName = "Calculator",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 18,
                            CategoryName = "Building Maintenance",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7910),
                            Description = "Building and facility maintenance",
                            DisplayOrder = 18,
                            IconName = "Factory",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 19,
                            CategoryName = "Repairs",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7912),
                            Description = "General repair expenses",
                            DisplayOrder = 19,
                            IconName = "Hammer",
                            IsActive = true,
                            IsSystemCategory = true
                        },
                        new
                        {
                            ExpenseCategoryId = 20,
                            CategoryName = "Miscellaneous",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7914),
                            Description = "Other miscellaneous expenses",
                            DisplayOrder = 20,
                            IconName = "DotsHorizontal",
                            IsActive = true,
                            IsSystemCategory = true
                        });
                });

            modelBuilder.Entity("FactoryManagement.Models.FinancialTransaction", b =>
                {
                    b.Property<int>("FinancialTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("LinkedLoanAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("FinancialTransactionId");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("LinkedLoanAccountId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("FactoryManagement.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ItemName");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7794),
                            CurrentStock = 1000m,
                            ItemName = "Rice",
                            Unit = "Kg"
                        },
                        new
                        {
                            ItemId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7799),
                            CurrentStock = 500m,
                            ItemName = "Husk",
                            Unit = "Kg"
                        },
                        new
                        {
                            ItemId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7800),
                            CurrentStock = 2000m,
                            ItemName = "Paddy",
                            Unit = "Kg"
                        },
                        new
                        {
                            ItemId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7802),
                            CurrentStock = 300m,
                            ItemName = "Broken Rice",
                            Unit = "Kg"
                        },
                        new
                        {
                            ItemId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7803),
                            CurrentStock = 150m,
                            ItemName = "Bran",
                            Unit = "Kg"
                        });
                });

            modelBuilder.Entity("FactoryManagement.Models.LoanAccount", b =>
                {
                    b.Property<int>("LoanAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LoanType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanAccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DueDate");

                    b.HasIndex("LoanType");

                    b.HasIndex("PartyId");

                    b.HasIndex("Status");

                    b.ToTable("LoanAccounts");
                });

            modelBuilder.Entity("FactoryManagement.Models.OperationalExpense", b =>
                {
                    b.Property<int>("OperationalExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpentBy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TotalAmountWithTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("OperationalExpenseId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("IsApproved");

                    b.HasIndex("ItemId");

                    b.HasIndex("SpentBy");

                    b.ToTable("OperationalExpenses");
                });

            modelBuilder.Entity("FactoryManagement.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("Name");

                    b.HasIndex("PartyType");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7827),
                            MobileNumber = "9876543210",
                            Name = "ABC Traders",
                            PartyType = 2,
                            Place = "Mumbai"
                        },
                        new
                        {
                            PartyId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7830),
                            MobileNumber = "9876543211",
                            Name = "XYZ Suppliers",
                            PartyType = 1,
                            Place = "Delhi"
                        },
                        new
                        {
                            PartyId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7831),
                            MobileNumber = "9876543212",
                            Name = "PQR Distributors",
                            PartyType = 0,
                            Place = "Bangalore"
                        },
                        new
                        {
                            PartyId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7833),
                            MobileNumber = "9876543213",
                            Name = "LMN Enterprises",
                            PartyType = 2,
                            Place = "Chennai"
                        });
                });

            modelBuilder.Entity("FactoryManagement.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InputQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("InputItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FactoryManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7642),
                            IsActive = true,
                            Role = "Administrator",
                            Username = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7661),
                            IsActive = true,
                            Role = "Manager",
                            Username = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 13, 48, 11, 771, DateTimeKind.Local).AddTicks(7663),
                            IsActive = true,
                            Role = "Operator",
                            Username = "Operator"
                        });
                });

            modelBuilder.Entity("FactoryManagement.Models.WageTransaction", b =>
                {
                    b.Property<int>("WageTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AdvanceAdjusted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DaysWorked")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OvertimeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OvertimeHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OvertimeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WageTransactionId");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.HasIndex("WorkerId");

                    b.ToTable("WageTransactions");
                });

            modelBuilder.Entity("FactoryManagement.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeavingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAdvance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWagesPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WorkerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("FactoryManagement.Models.ExpenseCategory", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FactoryManagement.Models.FinancialTransaction", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("EnteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.LoanAccount", "LinkedLoanAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LinkedLoanAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FactoryManagement.Models.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedLoanAccount");

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FactoryManagement.Models.Item", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FactoryManagement.Models.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("FactoryManagement.Models.LoanAccount", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FactoryManagement.Models.OperationalExpense", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FactoryManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("EnteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("OperationalExpenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FactoryManagement.Models.User", "SpentByUser")
                        .WithMany()
                        .HasForeignKey("SpentBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Approver");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Item");

                    b.Navigation("SpentByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FactoryManagement.Models.Party", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FactoryManagement.Models.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("FactoryManagement.Models.Transaction", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("EnteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.Item", "InputItem")
                        .WithMany()
                        .HasForeignKey("InputItemId");

                    b.HasOne("FactoryManagement.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FactoryManagement.Models.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InputItem");

                    b.Navigation("Item");

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FactoryManagement.Models.WageTransaction", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("EnteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactoryManagement.Models.Worker", "Worker")
                        .WithMany("WageTransactions")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FactoryManagement.Models.Worker", b =>
                {
                    b.HasOne("FactoryManagement.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FactoryManagement.Models.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("FactoryManagement.Models.ExpenseCategory", b =>
                {
                    b.Navigation("OperationalExpenses");
                });

            modelBuilder.Entity("FactoryManagement.Models.LoanAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FactoryManagement.Models.Worker", b =>
                {
                    b.Navigation("WageTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
